// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.0
// source: api/main.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccessStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientID       string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ServiceID      string                 `protobuf:"bytes,2,opt,name=serviceID,proto3" json:"serviceID,omitempty"`
	UsageAmountReq uint64                 `protobuf:"varint,3,opt,name=usageAmountReq,proto3" json:"usageAmountReq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAccessStatusRequest) Reset() {
	*x = GetAccessStatusRequest{}
	mi := &file_api_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessStatusRequest) ProtoMessage() {}

func (x *GetAccessStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAccessStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_main_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccessStatusRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *GetAccessStatusRequest) GetServiceID() string {
	if x != nil {
		return x.ServiceID
	}
	return ""
}

func (x *GetAccessStatusRequest) GetUsageAmountReq() uint64 {
	if x != nil {
		return x.UsageAmountReq
	}
	return 0
}

type GetAccessStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAllowed         bool                   `protobuf:"varint,1,opt,name=isAllowed,proto3" json:"isAllowed,omitempty"`
	RetryAfterSeconds uint64                 `protobuf:"varint,2,opt,name=retryAfterSeconds,proto3" json:"retryAfterSeconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAccessStatusResponse) Reset() {
	*x = GetAccessStatusResponse{}
	mi := &file_api_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessStatusResponse) ProtoMessage() {}

func (x *GetAccessStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAccessStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_main_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessStatusResponse) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

func (x *GetAccessStatusResponse) GetRetryAfterSeconds() uint64 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

var File_api_main_proto protoreflect.FileDescriptor

const file_api_main_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/main.proto\"z\n" +
	"\x16GetAccessStatusRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12\x1c\n" +
	"\tserviceID\x18\x02 \x01(\tR\tserviceID\x12&\n" +
	"\x0eusageAmountReq\x18\x03 \x01(\x04R\x0eusageAmountReq\"e\n" +
	"\x17GetAccessStatusResponse\x12\x1c\n" +
	"\tisAllowed\x18\x01 \x01(\bR\tisAllowed\x12,\n" +
	"\x11retryAfterSeconds\x18\x02 \x01(\x04R\x11retryAfterSeconds2U\n" +
	"\vRateLimiter\x12F\n" +
	"\x0fGetAccessStatus\x12\x17.GetAccessStatusRequest\x1a\x18.GetAccessStatusResponse\"\x00B\x15Z\x13rate-limiter-go/apib\x06proto3"

var (
	file_api_main_proto_rawDescOnce sync.Once
	file_api_main_proto_rawDescData []byte
)

func file_api_main_proto_rawDescGZIP() []byte {
	file_api_main_proto_rawDescOnce.Do(func() {
		file_api_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_main_proto_rawDesc), len(file_api_main_proto_rawDesc)))
	})
	return file_api_main_proto_rawDescData
}

var file_api_main_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_main_proto_goTypes = []any{
	(*GetAccessStatusRequest)(nil),  // 0: GetAccessStatusRequest
	(*GetAccessStatusResponse)(nil), // 1: GetAccessStatusResponse
}
var file_api_main_proto_depIdxs = []int32{
	0, // 0: RateLimiter.GetAccessStatus:input_type -> GetAccessStatusRequest
	1, // 1: RateLimiter.GetAccessStatus:output_type -> GetAccessStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_main_proto_init() }
func file_api_main_proto_init() {
	if File_api_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_main_proto_rawDesc), len(file_api_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_main_proto_goTypes,
		DependencyIndexes: file_api_main_proto_depIdxs,
		MessageInfos:      file_api_main_proto_msgTypes,
	}.Build()
	File_api_main_proto = out.File
	file_api_main_proto_goTypes = nil
	file_api_main_proto_depIdxs = nil
}
